#!/usr/bin/env python3
'''Generate desktop file for yuki-iptv'''
import glob
import gettext

PREFIX = '''[Desktop Entry]
Type=Application
Name=yuki-iptv
Comment=IPTV player
'''

SUFFIX = '''Exec=yuki-iptv
Icon=yuki-iptv
Categories=AudioVideo;Video;Player;Recorder;TV;
Keywords=Television;Stream;
'''

FILE = open('./usr/share/applications/yuki-iptv.desktop', 'w', encoding='utf8')
FILE.write(PREFIX)

for lang_file in glob.glob('./po/yuki-iptv-*.po'):
    lang = lang_file.replace('.po', '').split('-')[2]
    translation = gettext.translation('yuki-iptv', './usr/share/locale/', languages=[lang])
    playername = translation.gettext('IPTV player')
    if playername != 'IPTV player' and lang != 'en':
        FILE.write("Comment[{}]={}\n".format(lang, playername))

FILE.write(SUFFIX)
FILE.close()
