#!/bin/sh
cd "$(dirname "$(realpath "$0")")" || exit 1
xgettext --language=Python --keyword=_ --package-name=yuki-iptv --output=yuki-iptv.pot usr/lib/yuki-iptv/yuki-iptv.py usr/lib/yuki-iptv/yuki_iptv/*.py
